#!/usr/bin/env bash
CHOICE_FILE="$HOME/.irkk-choice"
choice=0

if [ "$1" == "-f" ] || [ "$1"  == "--force" ]; then
    echo -e "You've choosen to replace yor irkk choice.\n"

    # Check if user already has screen running.
    # Note that these "booleans" are inverted
    hasScreen=$(screen -ls | grep -c irkk)
    hasTmux=$(tmux list-sessions 2>/dev/null | grep -c irkk)
    goahead="true"

    if [ "$hasScreen" -gt "0" ] || [ "$hasTmux" -gt "0" ]; then
        echo "Please note that you have a session running already."
        echo -e "Do you want to replace it with a new choice?\n(note that your IRC connection will be disconnected)"
        select answer in "Yes please" "Hell no!"; do
        case $answer in
            "Yes please" ) goahead="true"; break ;;
            "Hell no!" ) goahead="false"; break;;
        esac
    done
    fi

    if [ "$goahead" == "true" ]; then
        if [ "$hasScreen" -gt "0" ]; then
            screen -S irkk -X quit
        elif [ "$hasTmux" -gt "0" ]; then
            tmux kill-session -t irkk
        fi

        [ ! -f $CHOICE_FILE ] || eval "rm $CHOICE_FILE"
    fi
fi

# No previous choice
if [ ! -f $CHOICE_FILE ]; then
    echo -e "(run 'irkk -f' if you were unsatisfied with your choice)\nDo you want to use:"
    weechatScreen="WeeChat in Screen"
    irssiScreen="Irssi in Screen"
    weechatTmux="WeeChat in tmux"
    irssiTmux="Irssi in tmux (recommended)"
    select answer in "$weechatScreen" "$irssiScreen" "$weechatTmux" "$irssiTmux"; do
        case $answer in
            $weechatScreen ) eval "echo 1 >$CHOICE_FILE"; break ;;
            $irssiScreen ) eval "echo 2 >$CHOICE_FILE"; break;;
            $weechatTmux ) eval "echo 3 >$CHOICE_FILE"; break;;
            $irssiTmux ) eval "echo 4 >$CHOICE_FILE"; break;;
        esac
    done
fi

choice=$(eval "cat $CHOICE_FILE")

case $choice in
    1 ) screen -xRR irkk -qd /usr/bin/weechat-curses ;;
    2 ) screen -xRR irkk -qd irssi ;;
    3 ) tmux attach-session -t irkk || tmux new-session -s irkk /usr/bin/weechat-curses ;;
    4 ) tmux attach-session -t irkk || tmux new-session -s irkk irssi ;;
esac
